### ISSUE TITLE
Timetable of paper and code release

### ISSUE THREAD

**Issue by rcao-hk** [hetolin/SAR-Net#1]
Hi Haitao,

Thank you for your excellent work!
Could you please tell me the time that I can access the paper and code?

Regards,
Rui

**Comment by hetolin** [comment]
Hi, Thank you for your interest in our work!
For the paper, we have updated the paper on the arXiv website recently. Here is the [link](https://arxiv.org/abs/2106.14193)
For the code, we are currently organizing the code, and will release the code later. We will inform you once the code is publicly available.

**Comment by rcao-hk** [comment]
Hi, Haitao

Thank you for your reply. How I can find the Appendix part mentioned in the paper?

Best,
Rui

**Comment by hetolin** [comment]
Hi,

I will update the Appendix to the GitHub soon.

**Comment by hetolin** [comment]
Hi, I have uploaded the Appendix [supp](https://github.com/hetolin/SAR-Net/blob/main/SARNet_supp.pdf) on the Github.

**Comment by scq6688** [comment]
期待您将神经网络部分开源

**Comment by hetolin** [comment]
@scq6688 谢谢，我们开源后会第一时间告知您的

**Comment by kannwism** [comment]
Hi Hetolin,

I find your approach really interesting and would like to try out the code. I hope find the time to upload it soon!

Thanks!

**Comment by hetolin** [comment]
Hi, the code is released now
