### ISSUE TITLE
camera_train_processed 文件

### ISSUE THREAD

**Issue by zhu-wanru** [hetolin/SAR-Net#11]
您好！我想要下载Readme中所提到的camera_train_processed文件，但是点击后，并没有获得文件下载网址。随后发现链接指向的是开源代码界面，能问一下要怎么下载这个文件呢？

**Comment by hetolin** [comment]
你好，这个文件我稍后会上传到谷歌云盘

**Comment by hetolin** [comment]
@Wanru0820 数据已上传 [camera_train_processed](https://drive.google.com/file/d/1DzqX5OQIOo44viQepPXZfWUXmb1WLZhc/view?usp=share_link)
