### ISSUE TITLE
提供的test和val数据集下缺list.txt文件

### ISSUE THREAD

**Issue by capf-2011** [hetolin/SAR-Net#13]
您好，能不能提供一下data文件夹下CAMERA/val_list.txt和Real/test_list.txt这两个文件，谢谢

**Comment by hetolin** [comment]
您好,[CAMERA/val_list.txt](https://github.com/hetolin/SAR-Net/blob/main/data/NOCS/CAMERA/val_list.txt)和[Real/test_list.txt](https://github.com/hetolin/SAR-Net/blob/main/data/NOCS/Real/test_list.txt)已经包含在代码中了

**Comment by capf-2011** [comment]
好的，谢谢您

**Comment by capf-2011** [comment]
另外，我想问一下您 @hetolin ，这个错误是不是缺相关的_label.pkl文件呀，能不能受累提供一下，或者提供一下生成代码，谢谢
![图片](https://github.com/hetolin/SAR-Net/assets/49231801/e9d271b4-259e-4400-93cb-269bb869ce29)
关于evaluate的318行代码        with open(img_path + '_label.pkl', 'rb') as f:
            gts = cPickle.load(f)

**Comment by hetolin** [comment]
你可以用这个代码来生成的,[pose_data.py](https://github.com/mentian/object-deformnet/blob/master/preprocess/pose_data.py). 我晚些也会上传处理好的_label.pkl文件

**Comment by capf-2011** [comment]
> 你可以用这个代码来生成的,[pose_data.py](https://github.com/mentian/object-deformnet/blob/master/preprocess/pose_data.py). 我晚些也会上传处理好的_label.pkl文件

好的，谢谢

**Comment by hetolin** [comment]
@capf-2011 CAMERA的_label.pkl是在每个子文件中，好像不太好单独下载，你要不直接按照[object-deformnet](https://github.com/mentian/object-deformnet)这个里面的[pose_data.py](https://github.com/mentian/object-deformnet/blob/master/preprocess/pose_data.py)代码处理一下吧，就可以得到对应的_label.pkl文件了

**Comment by capf-2011** [comment]
> @capf-2011 CAMERA的_label.pkl是在每个子文件中，好像不太好单独下载，你要不直接按照[object-deformnet](https://github.com/mentian/object-deformnet)这个里面的[pose_data.py](https://github.com/mentian/object-deformnet/blob/master/preprocess/pose_data.py)代码处理一下吧，就可以得到对应的_label.pkl文件了
我发现pose_data.py处理的时候，NOCS/gts里面有些文件内容没有nocs['gt_class_ids']或者nocs['gt_handle_visibility']，是我处理不当还是什么原因，可以忽略么，能不能解释一下

**Comment by hetolin** [comment]
@capf-2011 我上传了preprocess代码，并更新了readme.md,
nocs['gt_class_ids']这个需要下载[[nocs_results](https://drive.google.com/file/d/1p72NdY4Bie_sra9U8zoUNI4fTrQZdbnc/view?usp=sharing)]这个文件夹。

你可以按照readme.md的Prepare Dataset部分处理一下数据即可

**Comment by capf-2011** [comment]
> @capf-2011 我上传了preprocess代码，并更新了readme.md, nocs['gt_class_ids']这个需要下载[[nocs_results](https://drive.google.com/file/d/1p72NdY4Bie_sra9U8zoUNI4fTrQZdbnc/view?usp=sharing)]这个文件夹。
> 
> 你可以按照readme.md的Prepare Dataset部分处理一下数据即可

可以了，谢谢

**Comment by jiguanglu** [comment]
> 您好，能不能提供一下data文件夹下CAMERA/val_list.txt和Real/test_list.txt这两个文件，谢谢

帅哥，能否提供一下联系方式，或者您加我，想咨询点项目上的问题。
我的微信：23124264
