### ISSUE TITLE
斯坦福拒绝下载NOCS数据集

### ISSUE THREAD

**Issue by HMCCMH** [hetolin/SAR-Net#14]
您好！斯坦福官网最近貌似拒绝了数据集的下载，请问您有gts.zip文件的源能分享一下吗？谢谢您

**Comment by corpse-dog** [comment]
请问能分享一下CAMERA/val、Real/test、gts、obj_models、nocs_esults数据集吗，我打开链接的时候闪退了，非常感谢。

**Comment by hetolin** [comment]
这几个数据集比较大，我也是从别人的网盘下载的，你再试试？我刚刚点了一下链接，是可以下载的

**Comment by qietingfengyin123** [comment]
求大佬分享CAMERA/val、Real/test、gts、obj_models、nocs_esults数据集，我下载不了

**Comment by hetolin** [comment]
我试了一下readme里面的下载链接，是可以正常下载的

**Comment by qietingfengyin123** [comment]
非常感谢！





------------------ 原始邮件 ------------------
发件人: 林海涛 | Haitao Lin ***@***.***&gt;
发送时间: 2024年7月20日 14:05
收件人: hetolin/SAR-Net ***@***.***&gt;
抄送: Ww_Kong ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [hetolin/SAR-Net] 斯坦福拒绝下载NOCS数据集 (Issue #14)





 
我试了一下readme里面的下载链接，是可以正常下载的
