### ISSUE TITLE
如何制作自己的数据集？

### ISSUE THREAD

**Issue by HMCCMH** [hetolin/SAR-Net#15]
您好！您的工作非常棒！非常值得学习！如果我们想跑自己的场景，该如何制作数据集？您能指导下制作的步骤吗？

**Comment by hetolin** [comment]
谢谢您对我们工作的关注！
如果训练位姿估计网络SAR-Net,可以把模型放到blender(例如，[stanford-shapenet-renderer](https://github.com/panmari/stanford-shapenet-renderer))从各个角度进行渲染得到深度图和相机外参，把深度图投影出来的到点云即可，将数据处理成[camera_train_processed](https://drive.google.com/file/d/1DzqX5OQIOo44viQepPXZfWUXmb1WLZhc/view?usp=share_link)这种格式即可

如果要训练3D-GCN,就需要把物体放在平面上，类似NOCS数据集的制作方法，然后抠取区域点云进行训练
