### ISSUE TITLE
在CAMERA25上训练的模型在REAL275上达不到论文上的效果问题

### ISSUE THREAD

**Issue by HMCCMH** [hetolin/SAR-Net#16]
您好！再次打扰您！
我利用您开源的代码并且根据您发布的制作预处理数据的步骤完成了模型所需的各个输入文件。我利用CAMERA25训练集训完模型（4卡v100进行，batch_size改为64，num_workers改为64，epoch为100，其他没有变化）后，对CAMERA25的test集和REAL275的测试集进行了测试，在CAMERA25的测试集上的结果非常好，与原论文一样；但是在REAL275测试集上的效果比较差，结果如下所示：
mAP:
3D IoU at 25: 81.0
3D IoU at 50: 69.7
3D IoU at 75: 26.3
5 degree, 2cm: 26.3
5 degree, 5cm: 37.1
10 degree, 2cm: 44.4
10 degree, 5cm: 64.7
10 degree, 10cm: 66.4
Acc:
3D IoU at 25: 89.7
3D IoU at 50: 81.3
3D IoU at 75: 42.5
5 degree, 2cm: 41.8
5 degree, 5cm: 50.8
10 degree, 2cm: 58.4
10 degree, 5cm: 72.5
一开始我们以为是增大了batch_size后epoch没变，更新的次数变少了，于是我们增加了epoch的数量，达到300，再次对REAL275进行了测试，结果如下：
mAP:
3D IoU at 25: 80.8
3D IoU at 50: 69.1
3D IoU at 75: 26.0
5 degree, 2cm: 25.9
5 degree, 5cm: 37.1
10 degree, 2cm: 46.9
10 degree, 5cm: 66.4
10 degree, 10cm: 68.5
Acc:
3D IoU at 25: 89.4
3D IoU at 50: 80.6
3D IoU at 75: 43.2
5 degree, 2cm: 41.4
5 degree, 5cm: 50.4
10 degree, 2cm: 60.6
10 degree, 5cm: 74.1
请问在数据处理的过程中，是有什么先后顺序吗？

**Comment by hetolin** [comment]
数据处理的过程中，没有先后顺序的,
4卡的话可以按照config/config_sarnet.py里面的[epoch=32*4, warm_up=2](https://github.com/hetolin/SAR-Net/blob/b14cf9d0b9a2ffb9f153206210bec2ebf3f1b560/config/config_sarnet.py#L18)的配置来训练,我们提供的pretrained model(epoch 99)是我用单卡2080ti, batch_size=32,epoch=100,的情况下训练出来的,重构了代码之后,我用4卡2080ti,训出来的结果和单卡的结果(论文里面的结果)差不多的,你可以改一下config再试试,我晚些也会用发布的数据在训一遍看看

**Comment by hetolin** [comment]
还有一点要注意的是,因为原来NOCS的代码中[计算IoU](https://github.com/hetolin/SAR-Net/blob/b14cf9d0b9a2ffb9f153206210bec2ebf3f1b560/lib/utils_pose.py#L336)的时候有一些小bug,修复bug后,导致3D IoU50和IoU75的结果会比原文低,你可以改回去看看

**Comment by HMCCMH** [comment]
您好！首先非常感谢您快速的回复！
我尝试了下将IoU计算改回修复bug前的，然后IoU75的结果提升了很多，请问在那个计算3D IoU的地方，axis=0和axis=1的区别在于比较的是前面xyz坐标系中的最大最小还是后面的N个点的最大最小吗？那么您的论文是使用原本NOCS的评估方式吗？

**Comment by hetolin** [comment]
是的，axis=0和axis=1的区别在于比较的是前面xyz坐标系中的最大最小和后面的N个点的最大最小。之前基本所有baseline论文都是用的原本NOCS的评估方式，所以我们论文也保持了原本NOCS的评估方式。

**Comment by hetolin** [comment]
@HMCCMH 你好，我用4卡2080ti，batch_size=32*4, warmup_epochs=2的情况下，基于[[camera_train_processed](https://drive.google.com/file/d/1DzqX5OQIOo44viQepPXZfWUXmb1WLZhc/view?usp=share_link)]重新训练了100 epochs，在REAL275上的结果和原文是基本一致的（3D IoU因为没有采用原NOCS的评估方式，所以对比原文略有降低）
<img width="1392" alt="image" src="https://github.com/hetolin/SAR-Net/assets/37474466/1412484a-69a3-450d-bcea-7cf01e63c72f">

**Comment by HMCCMH** [comment]
非常感谢您的再一次展示，我最近在使用您的模型跑现实物体的位姿估计，想请问您，d435直接出来的深度图就能直接使用吗？我现在使用梅卡曼德的深度图，但它的通道格式都是不符合这个模型的（梅卡曼德的深度图是tiff32位），这个模型需要转换成uint16类型的png图，我转换后深度图后出来的效果好像不太对劲，然后我查看了下中间的保存文件pcd，感觉也不太对。那么深度图除uint16类型的png的要求外是还有什么其他必须要求吗？

**Comment by hetolin** [comment]
是的,我们的demo就是用d435直接出来的深度图,梅卡曼德的深度图效果很好,应该位姿估计会更准,梅卡是4通道的uint8,我之前试过转成单通道的uint16就行了

**Comment by HMCCMH** [comment]
我觉得我的深度图转换的应该是对的，是不是不能使用bounding box而作为中间结果，必须得使用分割后的mask作为这个网络模型的输入，因为我输出了中间文件，发现使用了bounding box作为该模型的输入时，中间得到的backproj_pcd(这里的backproj_pcd指的是depth2pcd函数得到的backproj_pcd)就会是处于同一平面上的点云了(用MeshLab显示下中间的结果)，这里还是有点纳闷的；另外对于rmin，rmax，cmin，cmax，我看maskrcnn的结果输入是y1x1y2x2，但根据代码来看应该是使用y1y2x1x2？

**Comment by HMCCMH** [comment]
您好，我的问题已经解决了。
