### ISSUE TITLE
如何进行推理

### ISSUE THREAD

**Issue by DonDajie** [hetolin/SAR-Net#18]
您好，这个代码有训练，评估文件。但是我没有找到推理。

**Comment by hetolin** [comment]
您好，推理代码其实把evaluate.py的输入改成你自己的RGB-D图片和对应的预测mask就行了，[Line159](https://github.com/hetolin/SAR-Net/blob/dbf4b2317bb225593ec105f697a5f37bf1b071f5/evaluate.py#L159)和[Lin188](https://github.com/hetolin/SAR-Net/blob/dbf4b2317bb225593ec105f697a5f37bf1b071f5/evaluate.py#L188)

**Comment by hetolin** [comment]
已更新demo.py文件，可以直接对自己采集的图片进行更新
