### ISSUE TITLE
请问可以同时对多个物体进行6d姿态跟踪吗？

### ISSUE THREAD

**Issue by DonDajie** [hetolin/SAR-Net#19]
如何对多个物体就行6d姿态跟踪

**Comment by hetolin** [comment]
SAR-Net只能对物体进行位姿预测，可以用SAM+XMem对多物体的2D Mask进行逐一跟踪，然后得到每个物体的点云P_1, ...Pn，分别送入SAR-Net进行实时进行位姿估计，来模拟跟踪的效果
