### ISSUE TITLE
求学

### ISSUE THREAD

**Issue by Anqunious** [hetolin/SAR-Net#2]
大佬，能把代码开源一下吗/

**Comment by hetolin** [comment]
非常感谢您对我们工作的关注！
我们近期正在整理代码和模型，开源后会第一时间通知您。

**Comment by Anqunious** [comment]
请问代码支持Windows系统吗？

**Comment by hetolin** [comment]
应该是支持的，windows装上anaconda,配置好环境就行，我们的SAR-Net代码环境非常简单

**Comment by hetolin** [comment]
@Anqunious 你好，目前代码已经开源啦
