### ISSUE TITLE
evaluate.py的使用问题

### ISSUE THREAD

**Issue by yevra3** [hetolin/SAR-Net#21]
作者您好，我按照readme进行相关配置后，运行evaluate.py，会在175行，189行等处报错，无法检索到“pred_class_ids”等关键字。使用的数据集是readme中提到的的[mrcnn_mask_results]。我在该数据集pkl文件编码后的结果中找不到“bbox”，我需要对该数据集先行做什么处理吗？

**Comment by hetolin** [comment]
你好，你可以在172行mrcnn_result = cPickle.load(f, encoding='latin1')后面把print(mrcnn_result)出来看看？我感觉可能是pkl文件没读进去？

**Comment by yevra3** [comment]
谢谢您的回复与帮助。pkl文件被读到了，但是和evaluate.py的相关代码不匹配，参照demo.py修改，同时删除相关关键字中的“pred”就可以使用了。
