### ISSUE TITLE
请问可以开源 相机实施捕捉的代码 吗？

### ISSUE THREAD

**Issue by Tianyi20** [hetolin/SAR-Net#22]
hi!

really like your work! 我现在想要把您的offline的算法部署到实时相机上面，请问有可以开源的realtime相机的代码吗？

**Comment by Tianyi20** [comment]
我发现我需要得到mask-rcnn 的训练的结果来进行online的部署，请问您使用的mask-rcnn是什么？如果可以方便分享以下mask-rcnn的pretrained weight吗？

**Comment by hetolin** [comment]
> hi!
> 
> really like your work! 我现在想要把您的offline的算法部署到实时相机上面，请问有可以开源的realtime相机的代码吗？

你好，realtime相机的代码已经开源，在我的另外一个开源库中[ROS_tool.py](https://github.com/hetolin/PourIt/blob/main/ROS_tool.py)，目前支持realsense和kinect

**Comment by hetolin** [comment]
> 我发现我需要得到mask-rcnn 的训练的结果来进行online的部署，请问您使用的mask-rcnn是什么？如果可以方便分享以下mask-rcnn的pretrained weight吗？

online部署的话，早期使用的是[yolov7 mask](https://github.com/WongKinYiu/yolov7/tree/main),现在推荐使用[grounding-sam](https://github.com/IDEA-Research/Grounded-Segment-Anything)比maskrcnn部署方便，实时性更高

**Comment by Tianyi20** [comment]
> > 我发现我需要得到mask-rcnn 的训练的结果来进行online的部署，请问您使用的mask-rcnn是什么？如果可以方便分享以下mask-rcnn的pretrained weight吗？
> 
> online部署的话，早期使用的是[yolov7 mask](https://github.com/WongKinYiu/yolov7/tree/main),现在推荐使用[grounding-sam](https://github.com/IDEA-Research/Grounded-Segment-Anything)比maskrcnn部署方便，实时性更高

非常感谢您提供的信息！！ 另外online部署时候，因为要得到predicate mask才能进行Pose estimation，这部分需要训练吗？比如使用[yolov7 mask](https://github.com/WongKinYiu/yolov7/tree/main) 去只生成cup或者Bottle特定物体的mask, 或者是mask rcnn 只训练让他只识别特定物体的mask。还是说只需要官方提供的基础的mask generation就可以了？

**Comment by hetolin** [comment]
Mask prediction不需要自己额外针对某个类别单独训练。比如用[yolov7 mask](https://github.com/WongKinYiu/yolov7/tree/main)提供的[pretrained model](https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-mask.pt)预测就行，然后滤出cup或者Bottle特定物体的mask

**Comment by Tianyi20** [comment]
> Mask prediction不需要自己额外针对某个类别单独训练。比如用[yolov7 mask](https://github.com/WongKinYiu/yolov7/tree/main)提供的[pretrained model](https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-mask.pt)预测就行，然后滤出cup或者Bottle特定物体的mask

理解了，非常感谢您！很喜欢您的作品，我计划做一个Online noetics realsense camera 部署。如果可以完成我会尝试pull到您的作品上！

**Comment by hetolin** [comment]
非常欢迎！期待您的更新
