### ISSUE TITLE
Request for Appendix file

### ISSUE THREAD

**Issue by Bingo-1996** [hetolin/SAR-Net#3]
作者你好，请问论文的补充材料在哪里啊？

**Comment by hetolin** [comment]
你好，补充材料的图片比较多，导致文件较大，没法上传arxiv，我后面会直接同步到github上

**Comment by hetolin** [comment]
你好，论文的补充材料[supp](https://github.com/hetolin/SAR-Net/blob/main/SARNet_supp.pdf)已上传

**Comment by Bingo-1996** [comment]
谢谢！
