### ISSUE TITLE
关于代码

### ISSUE THREAD

**Issue by touchthefish233** [hetolin/SAR-Net#5]
您好，关注您的工作两个月了，每个星期都会看看有没有开源，请问可以给个开源的准确时间吗？非常渴望能拜读您的代码

**Comment by hetolin** [comment]
您好，非常感谢您一直以来关注我们的工作，之前的代码写的太乱了，最近忙着其他事情一直没空去整理和测试，代码最晚会在7月底之前开源的，一旦开源了，我们会第一时间通知您

**Comment by touchthefish233** [comment]
非常感谢您在百忙之中进行回复，非常希望能早日看到您的代码，近日通过修改SPD的网络结构复现文章中提到的通过预测先验模型的旋转预测旋转，并不能达到文章中提到的结果，希望早日对比源代码找到错误所在。或许是因为3GCN对结果起到了重要的作用？如果可以能请您先一步开源3DGCN分割的代码吗？还有一个关于loss的问题，您私乎在论文中提到使用L1loss作为旋转预测的loss函数，您是如何比较L1loss跟倒角距离的优劣呢？

**Comment by sepzfq** [comment]
Looking forward to your project！！

**Comment by hetolin** [comment]
@touchthefish233 非常谢谢您对我们工作的关注，因为最近在做一些工程化的东西，可能暂时还不能开源，非常抱歉，SARNet网络结构其实挺简单的，具体结构都列在supplemental material里面了，应该挺容易复现的。关于具体开源时间还不能确定，等开源了第一时间马上告知您。其中3GCN的话有利于滤除背景的点云，避免SARNet网络在预测时容易把背景的点云当成物体的一部分来处理。3DGCN的话是用[3DGCN](https://github.com/zhihao-lin/3dgcn)实现的，用NOCS-CAMERA数据集训练。至于loss的话，L1 loss和倒角距离的优势感觉很难直接比较，因为SARNet里面L1 loss是用于点对点之间的直接监督，倒角距离的话感觉适用于全局形状约束。

**Comment by hetolin** [comment]
@sepzfq Thanks very much！

**Comment by hetolin** [comment]
Hi, the code is released now.
