### ISSUE TITLE
Question about SAR-Net Results

### ISSUE THREAD

**Issue by taeyeopl** [hetolin/SAR-Net#9]
I am interested in your work, and I am trying to compare the results of your method (SAR-Net, CVPR22).
**Can you share your method .pkl files of Table 1 on the REAL275??**
![image](https://user-images.githubusercontent.com/50736858/202059782-b2913157-461e-451f-a042-6c6a66550b11.png)

If you can share it quickly, it would be of great help.
My email is taeyeop.trevor@gmail.com

**Comment by hetolin** [comment]
Thanks for your interested in our work. I have uploaded the .pkl files  of SAR-Net on REAL dataset  to the [Google Drive](https://drive.google.com/file/d/1BQD6SDpIdOtb9AokDzmcY1oTKHWh68v6/view?usp=sharing).

**Comment by taeyeopl** [comment]
Thanks for your quick reply with the results.

I have checked the results, and it looks like your **result['pred_RTs']**  parameter doesn't consider scale, always, scale is one.
I used a similar this code https://github.com/hughw19/NOCS_CVPR2019/blob/78a31c2026a954add1a2711286ff45ce1603b8ab/utils.py#L467


![scene_1_0000_pred_pose_student](https://user-images.githubusercontent.com/50736858/202081109-d0ce81cc-5abb-4994-83ca-598e260d9ee9.png)

**Comment by hetolin** [comment]
Yes, the result['pred_RTs'] parameter doesn't consider scale, the predicted scale is stored in result['pred_scales']

**Comment by taeyeopl** [comment]
I initially considered the scale and looks fine.
This is my visualization code, and please feel free to let me know if there are any mistakes
![scene_1_0000_pred_pose_student](https://user-images.githubusercontent.com/50736858/202084394-23e15661-f1ee-4cf3-baf7-f312d5b22587.png)

```
# Reference code 
 (https://github.com/hughw19/NOCS_CVPR2019/blob/78a31c2026a954add1a2711286ff45ce1603b8ab/utils.py#L2833)
#xyz_axis = 0.3*np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0]]).transpose()
xyz_axis = np.array([[0, 0, 0], [0, 0, pred_size[i, 2]/2], [0, pred_size[i, 1]/2, 0], [pred_size[i, 0]/2, 0, 0]]).transpose()
transformed_axes = transform_coordinates_3d(xyz_axis, RT)
projected_axes = calculate_2d_projections(transformed_axes, intrinsics)
```

**Comment by hetolin** [comment]
Yeah, this visualization result is right

**Comment by taeyeopl** [comment]
Great!! Again, Thanks for your quick reply and for sharing the results.
